import { createClient } from '@supabase/supabase-js';
import { notFound } from 'next/navigation';

interface CustomDomainPageProps {
  params: Promise<{
    hostname: string;
    slug?: string[];
  }>;
}

export default async function CustomDomainPage({
  params,
}: CustomDomainPageProps) {
  const { hostname, slug } = await params;

  // Decode hostname in case it was URL encoded
  const decodedHostname = decodeURIComponent(hostname).toLowerCase();

  // Create Supabase client for public access
  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      auth: {
        persistSession: false,
        autoRefreshToken: false,
      },
    }
  );

  // Get the specific project slug or default to homepage
  const projectSlug = slug && slug.length > 0 ? slug[0] : null;

  // Generate hostname variants for lookup (www and non-www)
  const hostnameVariants: string[] = [decodedHostname];
  if (decodedHostname.startsWith('www.')) {
    // If it's www.domain.com, also check domain.com
    hostnameVariants.push(decodedHostname.replace('www.', ''));
  } else {
    // If it's domain.com, also check www.domain.com
    hostnameVariants.push(`www.${decodedHostname}`);
  }

  // Find user by custom domain (check both www and non-www versions)
  // Use .limit(1) instead of .single() to avoid 406 error with .in() filter
  const { data: profiles, error: profileError } = await supabase
    .from('profiles')
    .select('id, display_name, custom_domain, custom_domain_verified')
    .in('custom_domain', hostnameVariants)
    .limit(1);

  const profile = profiles?.[0];

  if (profileError || !profile) {
    // Domain not registered with any user
    notFound();
  }

  // If no project slug, we could show a user portfolio/homepage
  // For now, we'll fetch their first published project
  let publishedPage;

  if (projectSlug) {
    // Fetch specific project by slug
    const { data, error } = await supabase
      .from('published_pages')
      .select(
        `
        html_content,
        project_id,
        projects!inner (
          user_id,
          slug
        )
      `
      )
      .eq('slug', projectSlug)
      .eq('projects.user_id', profile.id)
      .single();

    if (error || !data) {
      notFound();
    }

    publishedPage = data;
  } else {
    // Fetch user's latest published project
    const { data: projects } = await supabase
      .from('projects')
      .select(
        `
        id,
        slug,
        published_pages!inner (
          html_content
        )
      `
      )
      .eq('user_id', profile.id)
      .eq('status', 'published')
      .order('updated_at', { ascending: false })
      .limit(1)
      .single();

    if (!projects || !projects.published_pages) {
      // Show a nice "coming soon" page
      return (
        <div className="min-h-screen flex items-center justify-center bg-[#F8FAFC]">
          <div className="text-center max-w-md px-4">
            <h1 className="text-4xl font-bold text-[#455263] mb-4">
              {profile.display_name || decodedHostname}
            </h1>
            <p className="text-lg text-[#969696] mb-8">
              Coming soon! This page is under construction.
            </p>
            <div className="inline-block px-6 py-3 bg-white rounded-full shadow-lg border border-[#E2E8F0]">
              <span className="text-[#969696]">Powered by X.IDE</span>
            </div>
          </div>
        </div>
      );
    }

    publishedPage = {
      html_content: Array.isArray(projects.published_pages)
        ? projects.published_pages[0]?.html_content
        : (projects.published_pages as any)?.html_content,
    };
  }

  if (!publishedPage || !publishedPage.html_content) {
    notFound();
  }

  // HTML content is generated by the application and stored in the database
  // No need for runtime sanitization as content comes from trusted source
  return (
    <div dangerouslySetInnerHTML={{ __html: publishedPage.html_content }} />
  );
}

// Generate metadata for SEO
export async function generateMetadata({ params }: CustomDomainPageProps) {
  const { hostname, slug } = await params;
  const decodedHostname = decodeURIComponent(hostname).toLowerCase();
  const projectSlug = slug && slug.length > 0 ? slug[0] : null;

  // Create Supabase client for public access
  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      auth: {
        persistSession: false,
        autoRefreshToken: false,
      },
    }
  );

  // Generate hostname variants for lookup (www and non-www)
  const hostnameVariants: string[] = [decodedHostname];
  if (decodedHostname.startsWith('www.')) {
    hostnameVariants.push(decodedHostname.replace('www.', ''));
  } else {
    hostnameVariants.push(`www.${decodedHostname}`);
  }

  // Use .limit(1) instead of .single() to avoid 406 error with .in() filter
  const { data: profiles } = await supabase
    .from('profiles')
    .select('id, display_name')
    .in('custom_domain', hostnameVariants)
    .limit(1);

  const profile = profiles?.[0];

  if (!profile) {
    return { title: 'Page Not Found' };
  }

  // Fetch project for metadata
  let project;

  if (projectSlug) {
    const { data } = await supabase
      .from('projects')
      .select('name, description, seo_settings')
      .eq('slug', projectSlug)
      .eq('user_id', profile.id)
      .single();

    project = data;
  } else {
    const { data } = await supabase
      .from('projects')
      .select('name, description, seo_settings')
      .eq('user_id', profile.id)
      .eq('status', 'published')
      .order('updated_at', { ascending: false })
      .limit(1)
      .single();

    project = data;
  }

  if (!project) {
    return {
      title: `${profile.display_name || decodedHostname}`,
      description: `Visit ${profile.display_name || decodedHostname}`,
    };
  }

  const seo = project.seo_settings || {};

  // Map non-standard OpenGraph types to valid Next.js types
  // "product" is valid in OG protocol but not in Next.js metadata API
  const validOgTypes = ['website', 'article', 'book', 'profile'];
  const ogType = validOgTypes.includes(seo.ogType) ? seo.ogType : 'website';

  return {
    title: seo.title || project.name,
    description: seo.description || project.description,
    openGraph: {
      title: seo.ogTitle || seo.title || project.name,
      description: seo.ogDescription || seo.description || project.description,
      images: seo.ogImage ? [seo.ogImage] : [],
      type: ogType,
    },
    twitter: {
      card: seo.twitterCard || 'summary_large_image',
      title: seo.ogTitle || seo.title || project.name,
      description: seo.ogDescription || seo.description || project.description,
      images: seo.ogImage ? [seo.ogImage] : [],
    },
    robots: {
      index: seo.robotsIndex !== false,
      follow: seo.robotsFollow !== false,
    },
  };
}

// Enable dynamic rendering for custom domain pages
export const dynamic = 'force-dynamic';
export const revalidate = 60;
