"use server";

import fs from "fs/promises";
import path from "path";

const DEMO_FILES: Record<number, string> = {
  18: "GradientDemo",
  25: "LoadingDemo",
  4: "TypographyDemo",
  26: "HoverDemo",
  12: "MicroInteractionDemo",
  27: "NeumorphicDemo",
  1: "RealTimeRenderingDemo",
  7: "LineAnimationDemo",
  8: "SelfDrawingDemo",
  9: "MorphingDemo",
  14: "Faux3DDemo",
  2: "ScrollytellingDemo",
  5: "CollaborativeDemo",
  15: "ScrollingEffectsDemo",
  22: "PageTransitionDemo",
  30: "FlipbookDemo",
  6: "AmbientBackgroundDemo",
  20: "AmbientBackgroundDemo",
  16: "MixedMediaDemo",
  17: "LiquidMotionDemo",
  28: "GlassmorphismDemo",
  29: "ClaymorphismDemo",
  10: "AnimatedLogoDemo",
  11: "AnimatedIconsDemo",
  13: "CharacterDemo",
  21: "DoodleDemo",
  31: "StopMotionDemo",
  3: "ARVRDemo",
  19: "IsometricDemo",
  23: "HeroSectionDemo",
  24: "SkeletonDemo",
  32: "InteractiveChartsDemo",
  33: "CircularProgressDemo",
  34: "NumberCounterDemo",
  35: "AudioWaveformDemo",
  36: "PricingTableDemo",
  37: "TestimonialCarouselDemo",
  38: "LogoMarqueeDemo",
  39: "CountdownTimerDemo",
  40: "ComparisonSliderDemo",
  41: "MegaMenuDemo",
  42: "ScrollProgressDemo",
  43: "AnimatedTabsDemo",
  44: "AccordionDemo",
  45: "SidebarCollapseDemo",
  46: "FloatingLabelDemo",
  47: "PasswordStrengthDemo",
  48: "FileUploadDemo",
  49: "MultiStepFormDemo",
  50: "AnimatedToggleDemo",
  51: "MagneticButtonDemo",
  52: "CursorTrailDemo",
  53: "ParallaxTiltDemo",
  54: "SpotlightRevealDemo",
  55: "MagnifyingGlassDemo",
  56: "ToastNotificationDemo",
  57: "SuccessMorphDemo",
  58: "ConfettiDemo",
  59: "AdvancedSkeletonDemo",
  60: "TextScrambleDemo",
  61: "TypewriterDemo",
  62: "VideoMaskDemo",
  63: "InteractiveGlobeDemo",
  64: "AiAssistantDemo",
  65: "CodeTypingDemo",
  66: "DynamicIslandDemo",
  67: "ParallaxDeviceDemo",
  68: "HolographicCardDemo",
  69: "LiquidTabBarDemo",
  70: "ParticleNetworkDemo",
  71: "StackedCardCarouselDemo",
  72: "CylinderScrollDemo",
  73: "GravityPhysicsGridDemo",
  74: "MorphingSvgLoaderDemo",
  75: "AudioVisualizerDemo",
  76: "BookFlipDemo",
  77: "ElasticDragDemo",
  78: "ColorPaletteGeneratorDemo",
  79: "WaterRippleDemo",
  80: "CubeSpinnerDemo",
  81: "MagnifiedDockDemo",
  82: "KanbanDragDropDemo",
  83: "StarFieldDemo",
  84: "StoryViewDemo",
  85: "ScratchCardDemo",
  86: "GradientFollowerDemo",
  87: "KineticTypographyDemo",
  88: "GridDistortionDemo",
  89: "FocusBlurRevealDemo",
  90: "MagneticGalleryDemo",
  91: "InfiniteTunnelDemo",
  92: "GlitchImageDemo",
  93: "ParticleTextDemo",
  94: "LiquidButtonDemo",
  95: "VerticalCardStackDemo",
  96: "MouseImageTrailDemo",
  97: "RetroGridScrollDemo",
  98: "DnaHelixDemo",
  99: "MatrixRainDemo",
  100: "FireworksDemo",
};

export async function getCode(id: number) {
  const filename = DEMO_FILES[id];
  if (!filename) return null;

  try {
    const filePath = path.join(process.cwd(), "src", "components", "demos", `${filename}.tsx`);
    const content = await fs.readFile(filePath, "utf-8");
    return content;
  } catch (error) {
    console.error(`Error reading file for ID ${id}:`, error);
    return null;
  }
}
