import { createClient } from '@supabase/supabase-js';
import { notFound, redirect } from 'next/navigation';

interface SubdomainPageProps {
  params: {
    subdomain: string;
    slug?: string[];
  };
}

export default async function SubdomainPage({ params }: SubdomainPageProps) {
  const { subdomain, slug } = params;

  // Create Supabase client for public access
  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      auth: {
        persistSession: false,
        autoRefreshToken: false,
      },
    }
  );

  // Get the specific project slug or default to homepage
  const projectSlug = slug && slug.length > 0 ? slug[0] : null;

  // Find user by subdomain
  const { data: profile, error: profileError } = await supabase
    .from('profiles')
    .select('id, display_name')
    .eq('subdomain', subdomain)
    .single();

  if (profileError || !profile) {
    notFound();
  }

  // If no project slug, redirect to the latest published project's slug
  if (!projectSlug) {
    const { data: latestProject } = await supabase
      .from('projects')
      .select('slug')
      .eq('user_id', profile.id)
      .eq('status', 'published')
      .order('updated_at', { ascending: false })
      .limit(1)
      .single();

    if (latestProject?.slug) {
      // Redirect to the project slug URL
      redirect(`/${latestProject.slug}`);
    } else {
      // No published projects - show coming soon page
      return (
        <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100">
          <div className="text-center max-w-md px-4">
            <h1 className="text-4xl font-bold text-gray-900 mb-4">
              {profile.display_name || subdomain}
            </h1>
            <p className="text-lg text-gray-600 mb-8">
              Coming soon! This page is under construction.
            </p>
            <div className="inline-block px-6 py-3 bg-white rounded-full shadow-lg">
              <span className="text-gray-500">Built with X.IDE</span>
            </div>
          </div>
        </div>
      );
    }
  }

  // Fetch specific project by slug
  const { data, error } = await supabase
    .from('published_pages')
    .select(`
      html_content,
      project_id,
      projects!inner (
        user_id,
        slug
      )
    `)
    .eq('slug', projectSlug)
    .eq('projects.user_id', profile.id)
    .single();

  if (error || !data) {
    notFound();
  }

  if (!data.html_content) {
    notFound();
  }

  // HTML content is generated by the application and stored in the database
  // No need for runtime sanitization as content comes from trusted source
  return (
    <div dangerouslySetInnerHTML={{ __html: data.html_content }} />
  );
}

// Generate metadata for SEO
export async function generateMetadata({ params }: SubdomainPageProps) {
  const { subdomain, slug } = params;
  const projectSlug = slug && slug.length > 0 ? slug[0] : null;

  // Create Supabase client for public access
  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      auth: {
        persistSession: false,
        autoRefreshToken: false,
      },
    }
  );

  const { data: profile } = await supabase
    .from('profiles')
    .select('id, display_name')
    .eq('subdomain', subdomain)
    .single();

  if (!profile) {
    return { title: 'Page Not Found' };
  }

  // Fetch project for metadata
  let project;

  if (projectSlug) {
    const { data } = await supabase
      .from('projects')
      .select('name, description, seo_settings')
      .eq('slug', projectSlug)
      .eq('user_id', profile.id)
      .single();

    project = data;
  } else {
    const { data } = await supabase
      .from('projects')
      .select('name, description, seo_settings')
      .eq('user_id', profile.id)
      .eq('status', 'published')
      .order('updated_at', { ascending: false })
      .limit(1)
      .single();

    project = data;
  }

  if (!project) {
    return {
      title: `${profile.display_name || subdomain} | X.IDE`,
      description: `Visit ${profile.display_name || subdomain}'s page`,
    };
  }

  const seo = project.seo_settings || {};

  return {
    title: seo.title || project.name,
    description: seo.description || project.description,
    openGraph: {
      title: seo.ogTitle || seo.title || project.name,
      description: seo.ogDescription || seo.description || project.description,
      images: seo.ogImage ? [seo.ogImage] : [],
      type: seo.ogType || 'website',
    },
    twitter: {
      card: seo.twitterCard || 'summary_large_image',
      title: seo.ogTitle || seo.title || project.name,
      description: seo.ogDescription || seo.description || project.description,
      images: seo.ogImage ? [seo.ogImage] : [],
    },
    robots: {
      index: seo.robotsIndex !== false,
      follow: seo.robotsFollow !== false,
    },
  };
}

// Enable dynamic rendering for subdomain pages
export const dynamic = 'force-dynamic';
export const revalidate = 60;
